# Generated by Django 5.1.1 on 2024-10-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onGoingProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjName', models.CharField(max_length=100)),
                ('prjDescription', models.CharField(max_length=200)),
                ('prjAgency', models.CharField(max_length=100)),
                ('prjAgencyLicense', models.FileField(upload_to='uploads/Agency')),
                ('prjFinance', models.FileField(upload_to='uploads/Finance')),
            ],
        ),
    ]
