# Generated by Django 5.1.1 on 2024-10-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('replyDept', models.CharField(default='Untitled Project', max_length=100)),
                ('replyDist', models.CharField(default='Untitled Project', max_length=100)),
                ('replyDescription', models.CharField(default='Untitled Project', max_length=300)),
            ],
        ),
    ]
