# Generated by Django 5.1.2 on 2024-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0003_ongoingprojects_deptname_ongoingprojects_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='Untitled Project', max_length=100)),
                ('password', models.CharField(default='Untitled Project', max_length=100)),
            ],
        ),
    ]
