# Generated by Django 5.1.2 on 2024-10-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0004_loginpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='makeObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('objection', models.CharField(max_length=100)),
            ],
        ),
    ]
